# Generated by Django 4.1.7 on 2023-04-13 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crystal_admin", "0003_addon_services_addon_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addon_services",
            name="addon_details",
        ),
        migrations.RemoveField(
            model_name="event_details",
            name="event_budget",
        ),
        migrations.RemoveField(
            model_name="order",
            name="addon_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="decoration_theam",
        ),
        migrations.RemoveField(
            model_name="order_items",
            name="addon_id",
        ),
        migrations.AlterField(
            model_name="bank_details",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crystal_admin.user",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crystal_admin.user",
            ),
        ),
        migrations.AlterField(
            model_name="event_details",
            name="manager_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crystal_admin.manager",
            ),
        ),
        migrations.AlterField(
            model_name="event_details",
            name="no_of_guest",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="event_details",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crystal_admin.user",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crystal_admin.user",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="manager_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="crystal_admin.manager",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crystal_admin.user",
            ),
        ),
    ]
