# Generated by Django 4.1.7 on 2023-04-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crystal_admin", "0006_alter_event_details_manager_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.FloatField(null=True),
        ),
    ]
