# Generated by Django 4.1.7 on 2023-04-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crystal_admin", "0007_order_subtotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="event_details",
            name="event_budget",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
