# Generated by Django 4.1.7 on 2023-05-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crystal_admin", "0008_event_details_event_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="decoration_theam",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
