# Generated by Django 4.1.7 on 2023-05-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crystal_admin", "0009_order_decoration_theam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event_details",
            name="event_date",
            field=models.DateField(),
        ),
    ]
